# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-04 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='address',
            field=models.TextField(max_length=1000, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(max_length=12, null=True, verbose_name='手机号'),
        ),
    ]
